### ISSUE TITLE
CGI.unescape vs. Rack::Utils.unescape/URI.decode_www_form_component?

### ISSUE THREAD

**Issue by AndrewO** [alext/invalid_utf8_rejector#5]
Hi Alex,

I'm trying to solve the same problem and I came across this project. I tracked down where my invalid UTF-8 strings were coming from through Rack::Utils.unescape down to URI.decode_www_form_component, so I figured whatever solution I came up with would probably use those.

I was wondering: why did you choose CGI.unescape here? Performance? More correct for this use-case? Any reason to prefer one over the other?

Thanks,
Andrew

**Comment by alext** [comment]
Hi, sorry this has sat for so long without a reply...

There wasn't a specific reason for cho0sing one over the other.  Having dug into rack itself a little more, I think `URI.decode_www_form_component` would be better as that's what `Rack::Request` uses.  I'll update this accordingly.

**Comment by alext** [comment]
Version 0.0.2 now released which uses `URI.decode_www_form_component` to be consistent with `Rack::Request`
